name: Build and Test v9.0

on:
  push:
    branches: [ v9.0 ]
  pull_request:
    branches: [ v9.0 ]
  schedule:
    - cron: 0 6 * * 1

jobs:
  build:
    name: build on ubuntu
        uses: actions/setup-dotnet@v1
        matrix:
          rid: [
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
      - name: Get Build Information
        run: |
          pwd
          dotnet --info
          dotnet --version
      - name: Build
        run: dotnet build --rid linux-x64
      - uses: actions/upload-artifact
  build-and-test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
      - name: Get Build Information
        run: |
          pwd
          dotnet --info
          dotnet --version
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal
